[package]
name = "onnx_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ort = "^2.0.0-alpha.4"
ndarray = "0.15.6"
